spring:
  application:
    name: service-registry

eureka:
  server:
    peer-node-read-timeout-ms: 2000
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka-server
    prefer-ip-address: true
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: health