services:
  zipkin-server:
    image: openzipkin/zipkin
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "9411:9411"
  redis-service:
    image: redis:latest
    container_name: redis-service
    expose:
      - "6379"
    networks:
      - microservices-network

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microservices-network
    environment:
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      gateway-service:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - microservices-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - microservices-network
    depends_on:
      elasticsearch:
        condition: service_started

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - microservices-network
    depends_on:
      elasticsearch:
        condition: service_started

  eureka-server:
    image: eureka-server:v1
    container_name: eureka-server
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8761/actuator/health"]
      interval: 50s
      timeout: 10s
      retries: 5
  config-server:
    image: config-server:v1
    container_name: config-server
    build:
      context: ./cloud-config-server
      dockerfile: Dockerfile
    expose:
      - "9196"
    networks:
        - microservices-network
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9196/actuator/health"]
      interval: 60s
      timeout: 20s
      retries: 10
  order-service:
    image: order-service:v1
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    expose:
      - "9092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - ORDER_SERVICE_PORT=9092
      - CONFIG_SERVER_URI=http://config-server:9196
      - ZIPKIN_HOST=zipkin-server
      - ZIPKIN_PORT=9411
    networks:
      - microservices-network
    depends_on:
      zipkin-server:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      logstash:
        condition: service_started
  payment-service:
    image: payment-service:v1
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    expose:
      - "9091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - PAYMENT_SERVICE_PORT=9091
      - CONFIG_SERVER_URI=http://config-server:9196
      - ZIPKIN_HOST=zipkin-server
      - ZIPKIN_PORT=9411
    networks:
      - microservices-network
    depends_on:
      zipkin-server:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      logstash:
        condition: service_started
  gateway-service:
    image: gateway-service:v1
    container_name: gateway-service
    build:
      context: ./cloud-gateway
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - CONFIG_SERVER_URI=http://config-server:9196
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - ZIPKIN_HOST=zipkin-server
      - ZIPKIN_PORT=9411
      - GATEWAY_PORT=8080
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/actuator/health"]
      interval: 60s
      timeout: 20s
      retries: 10
    depends_on:
      zipkin-server:
        condition: service_started
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      redis-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
volumes:
  esdata:
    driver: local
networks:
  microservices-network:
    driver: bridge