services:
  redis-service:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379"
    networks:
      - microservices-network
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-network
  config-server:
    image: config-server:latest
    container_name: config-server
    build:
      context: ./cloud-config-server
      dockerfile: Dockerfile
    ports:
      - "9196"
    networks:
        - microservices-network
    depends_on:
      - eureka-server
  order-service:
    image: order-service:latest
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "9092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - ORDER_SERVICE_PORT=9092
    networks:
      - microservices-network
    depends_on:
      - eureka-server
      - config-server

  payment-service:
    image: payment-service:latest
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "9091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - PAYMENT_SERVICE_PORT=9091
    networks:
      - microservices-network
    depends_on:
      - eureka-server
      - config-server

  gateway-service:
    image: gateway-service:latest
    container_name: gateway-service
    build:
      context: ./cloud-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - microservices-network
    depends_on:
      - eureka-server
      - order-service
      - payment-service
      - redis-service
      - config-server
networks:
  microservices-network:
    driver: bridge