services:
  zipkin-server:
    image: openzipkin/zipkin
    networks:
      - microservices-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "9411:9411"

  redis-service:
    image: redis:latest
    networks:
      - microservices-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    expose:
      - "6379"

  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microservices-network
    environment:
      - SERVER_NAME=${SERVER_NAME}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - microservices-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - microservices-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    environment:
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - microservices-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  eureka-server:
    image: eureka-server:v1
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  config-server:
    image: config-server:v1
    networks:
      - microservices-network
    expose:
      - "9196"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  order-service:
    image: order-service:v1
    networks:
      - microservices-network
    expose:
      - "9092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - ORDER_SERVICE_PORT=9092
      - CONFIG_SERVER_URI=http://config-server:9196
      - ZIPKIN_HOST=zipkin-server
      - ZIPKIN_PORT=9411
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  payment-service:
    image: payment-service:v1
    expose:
      - "9091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - PAYMENT_SERVICE_PORT=9091
      - CONFIG_SERVER_URI=http://config-server:9196
      - ZIPKIN_HOST=zipkin-server
      - ZIPKIN_PORT=9411
    networks:
      - microservices-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  gateway-service:
    image: gateway-service:v1
    expose:
      - "8080"
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - CONFIG_SERVER_URI=http://config-server:9196
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - ZIPKIN_HOST=zipkin-server
      - ZIPKIN_PORT=9411
      - GATEWAY_PORT=8080
    networks:
      - microservices-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  esdata:
    driver: local

networks:
  microservices-network:
    driver: overlay
