version: '3.8'

services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  order-service:
    image: order-service:latest
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "9092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - microservices-network
    depends_on:
      - eureka-server

  payment-service:
    image: payment-service:latest
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "9091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - microservices-network
    depends_on:
      - eureka-server

  gateway-service:
    image: gateway-service:latest
    container_name: gateway-service
    build:
      context: ./cloud-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - microservices-network
    depends_on:
      - eureka-server
      - order-service
      - payment-service

networks:
  microservices-network:
    driver: bridge