spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      routes:
        - id: order-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallback-url: forward:/orderFallback
        - id: payment-route
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallback-url: forward:/paymentFallback
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 5
              burstCapacity: 10
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  config:
    import: configserver:${CONFIG_SERVER_URI}
server:
  port: ${GATEWAY_PORT}
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - "*"
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
      connect-timeout: 5s
      read-timeout: 5s
    endpoint:
      health:
        show-details: always
logging:
  level:
    org.springframework.cloud.gateway.filter: TRACE
    org.springframework.cloud.gateway.handler: TRACE
    org.springframework.cloud.circuitbreaker: DEBUG
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.data.redis: DEBUG
    reactor.netty: DEBUG
    dev.alejandro.cloudgateway: INFO