spring:
  application:
    name: PAYMENT-SERVICE
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
  datasource:
    driver-class-name: org.h2.Driver
    name: payment-service
    url: jdbc:h2:mem:payment-service
  config:
    import: configserver:http://localhost:9196
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    config:
      initialize-on-context-refresh: true
server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
