spring:
  application:
    name: PAYMENT-SERVICE
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
  datasource:
    driver-class-name: org.h2.Driver
    name: payment-service
    url: jdbc:h2:mem:payment-service
server:
  port: 9091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance-info-replication-interval-seconds: 10
  instance:
    hostname: localhost