spring:
  application:
    name: ORDER-SERVICE
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
  datasource:
    driver-class-name: org.h2.Driver
    name: order-service
    url: jdbc:h2:mem:order-service
  config:
    import: configserver:http://localhost:9196
  zipkin:
    base-url: http://localhost:9411/
  main:
    allow-bean-definition-overriding: true
server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
    endpoint:
        health:
          show-details: always
  tracing:
    sampling:
      probability: 1.0
    enabled: true