spring:
  application:
    name: ORDER-SERVICE
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
  datasource:
    driver-class-name: org.h2.Driver
    name: order-service
    url: jdbc:h2:mem:order-service
  config:
    import: configserver:http://config-server:9196
server:
  port: ${ORDER_SERVICE_PORT}
